module.exports = {
  DISPLAY_FORMAT: 'L',
  ISO_FORMAT: 'YYYY-MM-DD',
  CUSTOM_FORMAT_1: 'DDMMYYYY',
  CUSTOM_FORMAT_2: 'YYYYMMDD',
  CUSTOM_FORMAT_3: 'DD/MM/YYYY',
  CUSTOM_FORMAT_4: 'YYYY/MM/DD',
  CUSTOM_FORMAT_5: 'DD-MM-YYYY',
  CUSTOM_FORMAT_6: 'DD.MM.YYYY',
  CUSTOM_FORMAT_7: 'YYYY.MM.DD',
  CUSTOM_FORMAT_8: 'DD_MM_YYYY',
  CUSTOM_FORMAT_9: 'YYYY_MM_DD',
  CUSTOM_FORMAT_10: 'DD MM YYYY',
  CUSTOM_FORMAT_11: 'YYYY MM DD',

  START_DATE: 'startDate',
  END_DATE: 'endDate',

  HORIZONTAL_ORIENTATION: 'horizontal',
  VERTICAL_ORIENTATION: 'vertical',
  VERTICAL_SCROLLABLE: 'verticalScrollable',

  ANCHOR_LEFT: 'left',
  ANCHOR_RIGHT: 'right',
};
